services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend